### ISSUE TITLE
bug: marker settings dialog label text is truncated for longer marker names

### ISSUE THREAD

**Issue by megahirt** [sillsdev/solid#25]
Longer marker names cause a text label to be cut off, potentially making it hard to understand what the label means.

e.g.

![image](https://github.com/sillsdev/solid/assets/3444521/c3f36c27-a527-4c30-bc97-d67f151274c5)

The label text should read:
**Under lx, marker_for_a_different_purpose can occur...**

There are a few different ways we could make this better:
- expand the cut-off area of the label
- move **can occur...** to the next line
- maybe both above, or something else entirely.

@bbryson do you have thoughts on this?

**Comment by bbryson** [comment]
I vote for "expand cutoff area" if that is easy.  In the two screenshots, notice that where it got cut off is different, because one says "After lx, marker..."   and the other says "After , marker...."   The latter is because I hadn't chosen a parent marker (e.g., lx) for it yet.  If the parent marker I chose had a longer name then lx, the cutoff would have been even earlier.

**Comment by josephmyers** [comment]
I just changed the text to a label and gave it word-wrapping. So it will now wrap to a second line!

**Comment by megahirt** [comment]
would love to have a screenshot or screencast demo of this!

**Comment by josephmyers** [comment]
![image](https://github.com/sillsdev/solid/assets/43733878/848f1d5b-afbe-4f02-9828-93190a8dd684)
